use css_styled::{StyledComponent, IntoCss, StyledComponentBase, css};

#[derive(StyledComponent, Clone)]
#[component(scope = "widget")]
#[component(class(inner = "widget-inner"))]
#[component(modifier(active))]
#[component(base_css)]
struct WidgetStyle {
    #[prop(var = "--w-size")]
    pub size: String,

    #[prop(var = "--w-color")]
    pub color: String,
}

impl Default for WidgetStyle {
    fn default() -> Self {
        Self {
            size: "100px".into(),
            color: "blue".into(),
        }
    }
}

impl StyledComponentBase for WidgetStyle {
    fn base_css() -> &'static str {
        css!(WidgetStyle, {
            SCOPE {
                width: var(--w-size);
                background: var(--w-color);
            }
            SCOPE.ACTIVE INNER {
                font-weight: bold;
            }
        })
    }
}

#[test]
fn css_vars_set_on_scope() {
    let style = WidgetStyle::default();
    let css = style.to_css();
    assert!(css.contains("--w-size: 100px"), "got: {css}");
    assert!(css.contains("--w-color: blue"), "got: {css}");
}

#[test]
fn base_css_references_vars() {
    let css = WidgetStyle::base_css();
    assert!(css.contains("var(--w-size)"), "got: {css}");
    assert!(css.contains("var(--w-color)"), "got: {css}");
}

#[test]
fn full_output() {
    let style = WidgetStyle::default();
    let css = style.to_css();
    // Base CSS with var() references
    assert!(css.contains("width: var(--w-size)"), "got: {css}");
    // Dynamic CSS with variable declarations
    assert!(css.contains("--w-size: 100px"), "got: {css}");
}

#[test]
fn var_consts_exist() {
    // These should be generated by the derive
    assert_eq!(WidgetStyle::VAR_W_SIZE, "--w-size");
    assert_eq!(WidgetStyle::VAR_W_COLOR, "--w-color");
}
